<template>
  <div class="space-y-4">
    <TextInput v-model="macInput" label="MAC 地址" placeholder="例如: 00:1B:63:84:45:E6 或 00-1B-63-84-45-E6 或 001B.6384.45E6" :rows="1" />

    <div class="flex justify-end">
      <button
        @click="lookup"
        :disabled="!macInput.trim()"
        class="btn-primary"
      >
        查询
      </button>
    </div>

    <ErrorAlert :message="error" />

    <div v-if="result" class="space-y-3">
      <div class="rounded-md border overflow-hidden" style="border-color: var(--color-border);">
        <table class="w-full text-sm">
          <tbody>
            <tr style="border-bottom: 1px solid var(--color-border);">
              <td class="px-4 py-2.5 font-medium" style="background-color: var(--color-bg-secondary); color: var(--color-text-secondary); width: 120px;">OUI 前缀</td>
              <td class="px-4 py-2.5 font-mono" style="color: var(--color-text);">{{ result.oui }}</td>
            </tr>
            <tr style="border-bottom: 1px solid var(--color-border);">
              <td class="px-4 py-2.5 font-medium" style="background-color: var(--color-bg-secondary); color: var(--color-text-secondary);">制造商</td>
              <td class="px-4 py-2.5" style="color: var(--color-text);">
                {{ result.vendor }}
                <CopyButton :text="result.vendor" />
              </td>
            </tr>
            <tr style="border-bottom: 1px solid var(--color-border);">
              <td class="px-4 py-2.5 font-medium" style="background-color: var(--color-bg-secondary); color: var(--color-text-secondary);">地址类型</td>
              <td class="px-4 py-2.5" style="color: var(--color-text);">{{ result.addressType }}</td>
            </tr>
            <tr>
              <td class="px-4 py-2.5 font-medium" style="background-color: var(--color-bg-secondary); color: var(--color-text-secondary);">完整地址</td>
              <td class="px-4 py-2.5 font-mono" style="color: var(--color-text);">
                {{ result.normalized }}
                <CopyButton :text="result.normalized" />
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="space-y-2">
        <div class="text-xs font-medium" style="color: var(--color-text-secondary);">格式转换</div>
        <div class="grid grid-cols-1 gap-2">
          <div v-for="fmt in formats" :key="fmt.label" class="flex items-center justify-between rounded-md border px-3 py-2" style="background-color: var(--color-bg-secondary); border-color: var(--color-border);">
            <div>
              <span class="text-xs font-medium mr-2" style="color: var(--color-text-secondary);">{{ fmt.label }}</span>
              <code class="text-xs font-mono" style="color: var(--color-text);">{{ fmt.value }}</code>
            </div>
            <CopyButton :text="fmt.value" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import TextInput from '../../common/TextInput.vue';
import ErrorAlert from '../../common/ErrorAlert.vue';
import CopyButton from '../../common/CopyButton.vue';

const macInput = ref('');
const error = ref('');

interface MacResult {
  oui: string;
  vendor: string;
  addressType: string;
  normalized: string;
}

const result = ref<MacResult | null>(null);

// OUI database (top ~50+ manufacturers)
const ouiDatabase: Record<string, string> = {
  '000000': 'Xerox Corporation',
  '00000C': 'Cisco Systems, Inc',
  '00000D': 'Fujitsu Limited',
  '00000E': 'Fujitsu Limited',
  '00001C': 'JDR Microdevices',
  '00001D': 'Cabletron Systems',
  '00001E': 'Telsist Industria Electronica',
  '00001F': 'Telco Systems',
  '00002A': 'TRW - SEDD/INP',
  '00004E': 'BBN Systems and Technologies',
  '00005A': 'SK Schmidt & Co.',
  '00005E': 'ICANN, IANA Department',
  '000066': 'TALARC Systems',
  '00007D': 'Cisco Systems, Inc',
  '00008C': 'Alloy Computer Products',
  '0000AA': 'Xerox Corporation',
  '0000C5': 'Ensim Corporation',
  '0000F8': 'Royal Melbourne Inst of Tech',
  '0001E6': 'Hewlett Packard',
  '0001F4': 'Enterasys Networks',
  '00021C': 'Cisco Systems, Inc',
  '00023F': 'Molex Incorporated',
  '000262': 'Soyo Group',
  '00036B': 'Cisco Systems, Inc',
  '000423': 'Intel Corporation',
  '00045A': 'D-Link Corporation',
  '00049F': 'Dell Inc.',
  '0004A3': 'Micron Technology, Inc.',
  '0004E2': 'SMC Networks, Inc.',
  '00059A': 'Cisco Systems, Inc',
  '0005BE': 'Kontron Embedded Modules GmbH',
  '00065B': 'Dell Inc.',
  '0007E9': 'Intel Corporation',
  '000874': 'Dell Inc.',
  '00095B': 'Netgear Inc.',
  '00096B': 'IBM Corporation',
  '00099B': 'Samsung Electronics Co., Ltd',
  '0009C5': 'Samsung Electronics Co., Ltd',
  '000B82': 'Grandstream Networks, Inc.',
  '000BD6': 'Cisco Systems, Inc',
  '000C41': 'Huawei Technologies Co., Ltd',
  '000C76': 'Huawei Technologies Co., Ltd',
  '000CF1': 'Intel Corporation',
  '000D56': 'Dell Inc.',
  '000D65': 'Cisco Systems, Inc',
  '000D88': 'D-Link Corporation',
  '000E08': 'Dell Inc.',
  '000E1E': 'Nvidia Corporation',
  '000E3B': 'Huawei Technologies Co., Ltd',
  '000ED6': 'Cisco Systems, Inc',
  '000F66': 'Cisco-Linksys, LLC',
  '001083': 'Hewlett Packard',
  '0010E3': 'Cisco Systems, Inc',
  '001109': 'Huawei Technologies Co., Ltd',
  '0011D8': 'ASRock Incorporation',
  '001217': 'Cisco Systems, Inc',
  '00127F': 'Dell Inc.',
  '001302': 'Intel Corporation',
  '00138F': 'Samsung Electronics Co., Ltd',
  '0013A9': 'Sony Corporation',
  '0013D5': 'Ruckus Wireless',
  '001423': 'Dell Inc.',
  '00146C': 'Netgear Inc.',
  '0014A5': 'Cisco Systems, Inc',
  '001517': 'Intel Corporation',
  '0015E0': 'Ericsson AB',
  '00163B': 'Samsung Electronics Co., Ltd',
  '0016CB': 'Apple, Inc.',
  '0016D4': 'Compal Electronics, Inc.',
  '00179A': 'D-Link Corporation',
  '0017C4': 'Quanta Microsystems, Inc.',
  '0017F2': 'Apple, Inc.',
  '001860': 'Huawei Technologies Co., Ltd',
  '0018DE': 'Intel Corporation',
  '0018F8': 'Samsung Electronics Co., Ltd',
  '00193D': 'Alcatel-Lucent',
  '0019CB': 'Apple, Inc.',
  '001B11': 'D-Link Corporation',
  '001B44': 'SanDisk Corporation',
  '001B63': 'Apple Inc.',
  '001C23': 'Dell Inc.',
  '001CB3': 'Apple, Inc.',
  '001D4F': 'Dell Inc.',
  '001D72': 'Wistron Corporation',
  '001DE0': 'Intel Corporation',
  '001E4C': 'Samsung Electronics Co., Ltd',
  '001E64': 'Huawei Technologies Co., Ltd',
  '001E65': 'Huawei Technologies Co., Ltd',
  '001E68': 'Quanta Computer Inc.',
  '001EC8': 'Rapid Mobile (Pty) Ltd',
  '001F16': 'Wistron Corporation',
  '001F3B': 'Intel Corporation',
  '001F5B': 'Apple, Inc.',
  '0020A6': 'Cisco Systems, Inc',
  '00211B': 'Dell Inc.',
  '002159': 'Apple, Inc.',
  '00215A': 'Huawei Technologies Co., Ltd',
  '002164': 'BitDefender',
  '0021CC': 'Dell Inc.',
  '002241': 'Huawei Technologies Co., Ltd',
  '002268': 'Cisco Systems, Inc',
  '0022B0': 'D-Link Corporation',
  '0022BD': 'Cisco Systems, Inc',
  '00235A': 'Huawei Technologies Co., Ltd',
  '0023DF': 'Apple, Inc.',
  '00241D': 'Samsung Electronics Co., Ltd',
  '002417': 'Cisco Systems, Inc',
  '002432': 'Huawei Technologies Co., Ltd',
  '00248C': 'LG Electronics',
  '0024D7': 'Intel Corporation',
  '002522': 'ASRock Incorporation',
  '002535': 'Huawei Technologies Co., Ltd',
  '00254B': 'Dell Inc.',
  '002556': 'Nokia Corporation',
  '00259C': 'Dell Inc.',
  '0025F7': 'Huawei Technologies Co., Ltd',
  '00260C': 'Dell Inc.',
  '0026B0': 'Apple, Inc.',
  '0026BB': 'Apple, Inc.',
  '0026C2': 'SCE Corporation',
  '0026C6': 'Intel Corporation',
  '0026F2': 'Nokia Corporation',
  '00270B': 'Dell Inc.',
  '00271E': 'Dell Inc.',
  '003008': 'Huawei Technologies Co., Ltd',
  '003018': 'Dell Inc.',
  '003048': 'Super Micro Computer, Inc.',
  '00304F': 'Dell Inc.',
  '00306E': 'Huawei Technologies Co., Ltd',
  '003088': 'Ericsson AB',
  '0030D9': 'Dell Inc.',
  '0030E6': 'Dell Inc.',
  '00311A': 'Cisco Systems, Inc',
  '00312A': 'Dell Inc.',
  '0050BA': 'D-Link Corporation',
  '0050F2': 'Microsoft Corporation',
  '0050FC': 'Edimax Technology Co., Ltd',
  '00E04C': 'Realtek Semiconductor Corp.',
  '00E04F': 'Cisco Systems, Inc',
  '00E098': 'Trend Micro Inc.',
  '00E09D': 'Cisco Systems, Inc',
  '00E0A4': 'Huawei Technologies Co., Ltd',
  '00E0B0': 'Cisco Systems, Inc',
  '00E0FC': 'Huawei Technologies Co., Ltd',
  '080001': 'Computervision Corporation',
  '080002': '3Com Corporation',
  '080007': 'Apple Computer, Inc.',
  '080008': 'BBN Systems and Technologies',
  '080009': 'Hewlett Packard',
  '08000B': 'Unisys Corporation',
  '08000C': 'Mikroelektronik',
  '08001A': 'Data General Corporation',
  '08001B': 'Data General Corporation',
  '08001F': 'Sharp Corporation',
  '080020': 'Oracle Corporation',
  '080026': 'Norsk Data A.S.',
  '08002B': 'Digital Equipment Corporation',
  '08003E': 'Motorola',
  '08004E': 'BBN Systems and Technologies',
  '08005A': 'IBM Corporation',
  '080069': 'Silicon Graphics, Inc.',
  '08006E': 'Tektronix, Inc.',
  '080074': 'Casio Computer Co., Ltd',
  '080079': 'Silicon Graphics, Inc.',
  '080089': 'Xerox Corporation',
  '3C15C2': 'Apple, Inc.',
  '3C2C3A': 'Huawei Technologies Co., Ltd',
  '3C2F3A': 'Huawei Technologies Co., Ltd',
  '3C3A73': 'Huawei Technologies Co., Ltd',
  '3C42B8': 'Huawei Technologies Co., Ltd',
  '3C591E': 'Tenda Technology Co., Ltd',
  '3C5A37': 'Samsung Electronics Co., Ltd',
  '3C5AB4': 'Google, Inc.',
  '3C672C': 'Intel Corporate',
  '3C6A2D': 'Huawei Technologies Co., Ltd',
  '3C81D8': 'Samsung Electronics Co., Ltd',
  '3C8C40': 'Huawei Technologies Co., Ltd',
  '3CBB96': 'Huawei Technologies Co., Ltd',
  '3CBD3E': 'Apple, Inc.',
  '3CD0F8': 'Huawei Technologies Co., Ltd',
  '3CE5A6': 'Huawei Technologies Co., Ltd',
  '3CE5B4': 'Samsung Electronics Co., Ltd',
  '3CF808': 'Huawei Technologies Co., Ltd',
  '3CFA21': 'Huawei Technologies Co., Ltd',
  '3CFA43': 'Huawei Technologies Co., Ltd',
  '402E28': 'Samsung Electronics Co., Ltd',
  '40428A': 'Huawei Technologies Co., Ltd',
  '404D8E': 'Huawei Technologies Co., Ltd',
  '404EEB': 'Huawei Technologies Co., Ltd',
  '40520D': 'Huawei Technologies Co., Ltd',
  '406186': 'D-Link International',
  '40618E': 'Huawei Technologies Co., Ltd',
  '406231': 'Huawei Technologies Co., Ltd',
  '407B0A': 'Huawei Technologies Co., Ltd',
  '407D0F': 'Huawei Technologies Co., Ltd',
  '40831E': 'Huawei Technologies Co., Ltd',
  '40A6D9': 'Apple, Inc.',
  '40A6E8': 'Huawei Technologies Co., Ltd',
  '40B0FA': 'Huawei Technologies Co., Ltd',
  '40B3CD': 'Apple, Inc.',
  '40B93C': 'Huawei Technologies Co., Ltd',
  '40BC60': 'Apple, Inc.',
  '40BD32': 'Huawei Technologies Co., Ltd',
  '40D32D': 'Apple, Inc.',
  '40E2ED': 'Huawei Technologies Co., Ltd',
  '40EC99': 'Intel Corporation',
  '40EE15': 'Samsung Electronics Co., Ltd',
  '48A195': 'Samsung Electronics Co., Ltd',
  '48A9D2': 'Wistron Corporation',
  '48B02D': 'Huawei Technologies Co., Ltd',
  '48B253': 'Apple, Inc.',
  '48B9C2': 'TP-Link Technologies Co., Ltd',
  '48C1AC': 'Huawei Technologies Co., Ltd',
  '48D705': 'Apple, Inc.',
  '48DCFB': 'Huawei Technologies Co., Ltd',
  '48E244': 'Apple, Inc.',
  '4C0BBE': 'Xiaomi Communications Co., Ltd',
  '4C1A95': 'Huawei Technologies Co., Ltd',
  '4C2F9E': 'Huawei Technologies Co., Ltd',
  '4C32D9': 'Huawei Technologies Co., Ltd',
  '4C49E3': 'Huawei Technologies Co., Ltd',
  '4C5690': 'Huawei Technologies Co., Ltd',
  '4C5E0C': 'Samsung Electronics Co., Ltd',
  '4C6B68': 'Huawei Technologies Co., Ltd',
  '4C74BF': 'Apple, Inc.',
  '4C77CB': 'Huawei Technologies Co., Ltd',
  '4C82CF': 'Huawei Technologies Co., Ltd',
  '4C8B30': 'Huawei Technologies Co., Ltd',
  '4C8B55': 'Huawei Technologies Co., Ltd',
  '4C8D79': 'Huawei Technologies Co., Ltd',
  '4C9EE4': 'Huawei Technologies Co., Ltd',
  '4CA003': 'Huawei Technologies Co., Ltd',
  '4CA515': 'Samsung Electronics Co., Ltd',
  '4CB76B': 'Huawei Technologies Co., Ltd',
  '4CB9C8': 'Huawei Technologies Co., Ltd',
  '4CE1BB': 'Huawei Technologies Co., Ltd',
  '4CE933': 'Huawei Technologies Co., Ltd',
  '500B91': 'Huawei Technologies Co., Ltd',
  '501479': 'Huawei Technologies Co., Ltd',
  '50267A': 'Huawei Technologies Co., Ltd',
  '502A7E': 'Huawei Technologies Co., Ltd',
  '503DE9': 'Huawei Technologies Co., Ltd',
  '505527': 'Huawei Technologies Co., Ltd',
  '5056A8': 'Huawei Technologies Co., Ltd',
  '506184': 'Huawei Technologies Co., Ltd',
  '506B8D': 'Intel Corporation',
  '5070E5': 'Huawei Technologies Co., Ltd',
  '5087B8': 'Huawei Technologies Co., Ltd',
  '508A06': 'Samsung Electronics Co., Ltd',
  '50A67F': 'Xiaomi Inc.',
  '50A6D8': 'Huawei Technologies Co., Ltd',
  '50B7C3': 'Huawei Technologies Co., Ltd',
  '50C7BF': 'Samsung Electronics Co., Ltd',
  '58A023': 'Intel Corporation',
  '5CF7E6': 'Huawei Technologies Co., Ltd',
  '60A4B0': 'Huawei Technologies Co., Ltd',
  '60F81D': 'Apple, Inc.',
  '64A5C3': 'Apple, Inc.',
  '64B0A6': 'Apple, Inc.',
  '64B9E8': 'Apple, Inc.',
  '64D2C4': 'Huawei Technologies Co., Ltd',
  '68DB54': 'Huawei Technologies Co., Ltd',
  '689C70': 'Apple, Inc.',
  '68A86D': 'Apple, Inc.',
  '68AB1E': 'Huawei Technologies Co., Ltd',
  '68D93C': 'Huawei Technologies Co., Ltd',
  '68FB7E': 'Huawei Technologies Co., Ltd',
  '70A8D3': 'Huawei Technologies Co., Ltd',
  '70B3D5': 'LG Electronics',
  '70D4F2': 'Huawei Technologies Co., Ltd',
  '70E422': 'Huawei Technologies Co., Ltd',
  '741489': 'Huawei Technologies Co., Ltd',
  '7446A0': 'Huawei Technologies Co., Ltd',
  '7451BA': 'Huawei Technologies Co., Ltd',
  '7490AF': 'Huawei Technologies Co., Ltd',
  '74A528': 'Huawei Technologies Co., Ltd',
  '74D02B': 'Samsung Electronics Co., Ltd',
  '74DE2B': 'Huawei Technologies Co., Ltd',
  '78028B': 'Huawei Technologies Co., Ltd',
  '7811DC': 'Huawei Technologies Co., Ltd',
  '7845C4': 'Dell Inc.',
  '784F43': 'Apple, Inc.',
  '785262': 'Huawei Technologies Co., Ltd',
  '78843D': 'Huawei Technologies Co., Ltd',
  '78A5DD': 'Huawei Technologies Co., Ltd',
  '78B81A': 'Huawei Technologies Co., Ltd',
  '78D004': 'Huawei Technologies Co., Ltd',
  '78D752': 'Huawei Technologies Co., Ltd',
  '78F5E5': 'Samsung Electronics Co., Ltd',
  '78F944': 'Huawei Technologies Co., Ltd',
  '7C2E0D': 'Huawei Technologies Co., Ltd',
  '7C70DB': 'Huawei Technologies Co., Ltd',
  '7CB232': 'Huawei Technologies Co., Ltd',
  '7CB77C': 'Huawei Technologies Co., Ltd',
  '80A1D7': 'Huawei Technologies Co., Ltd',
  '80D04B': 'Huawei Technologies Co., Ltd',
  '80E650': 'Apple, Inc.',
  '80EA23': 'Huawei Technologies Co., Ltd',
  '80FA5B': 'Huawei Technologies Co., Ltd',
  '84005E': 'Huawei Technologies Co., Ltd',
  '84788B': 'Huawei Technologies Co., Ltd',
  '84A134': 'Huawei Technologies Co., Ltd',
  '84A6C8': 'Intel Corporation',
  '84B153': 'Apple, Inc.',
  '84B802': 'Huawei Technologies Co., Ltd',
  '84C727': 'Huawei Technologies Co., Ltd',
  '88A4C2': 'Huawei Technologies Co., Ltd',
  '88B45D': 'Huawei Technologies Co., Ltd',
  '88C242': 'Huawei Technologies Co., Ltd',
  '88C9D0': 'Huawei Technologies Co., Ltd',
  '88CB87': 'Huawei Technologies Co., Ltd',
  '88CEFA': 'Huawei Technologies Co., Ltd',
  '8C1D96': 'Intel Corporation',
  '8C293F': 'Huawei Technologies Co., Ltd',
  '8C45A3': 'Huawei Technologies Co., Ltd',
  '8C53F7': 'Samsung Electronics Co., Ltd',
  '8C85C1': 'Huawei Technologies Co., Ltd',
  '8C8E90': 'Huawei Technologies Co., Ltd',
  '8CA048': 'Huawei Technologies Co., Ltd',
  '8CE081': 'Huawei Technologies Co., Ltd',
  '9003B7': 'Huawei Technologies Co., Ltd',
  '9017C8': 'Huawei Technologies Co., Ltd',
  '9024A8': 'Huawei Technologies Co., Ltd',
  '903C92': 'Apple, Inc.',
  '9049FA': 'Intel Corporation',
  '90671C': 'Huawei Technologies Co., Ltd',
  '907025': 'Huawei Technologies Co., Ltd',
  '909F33': 'Huawei Technologies Co., Ltd',
  '90B11C': 'Huawei Technologies Co., Ltd',
  '90B931': 'Apple, Inc.',
  '940B2D': 'Huawei Technologies Co., Ltd',
  '94103E': 'Huawei Technologies Co., Ltd',
  '941865': 'Huawei Technologies Co., Ltd',
  '9439E5': 'Huawei Technologies Co., Ltd',
  '9440A9': 'Huawei Technologies Co., Ltd',
  '944996': 'Huawei Technologies Co., Ltd',
  '946A77': 'Huawei Technologies Co., Ltd',
  '9496A5': 'Huawei Technologies Co., Ltd',
  '94AEE0': 'Huawei Technologies Co., Ltd',
  '94BF2D': 'Huawei Technologies Co., Ltd',
  '94CDAC': 'Huawei Technologies Co., Ltd',
  '94D9B3': 'Huawei Technologies Co., Ltd',
  '9801A7': 'Apple, Inc.',
  '9840BB': 'Huawei Technologies Co., Ltd',
  '984E97': 'Huawei Technologies Co., Ltd',
  '985DAD': 'Huawei Technologies Co., Ltd',
  '989C57': 'Huawei Technologies Co., Ltd',
  '98A40E': 'Huawei Technologies Co., Ltd',
  '98AF65': 'Huawei Technologies Co., Ltd',
  '98D293': 'Huawei Technologies Co., Ltd',
  '98D686': 'Huawei Technologies Co., Ltd',
  '98E7F5': 'Huawei Technologies Co., Ltd',
  '98FE03': 'Huawei Technologies Co., Ltd',
  '9C28F7': 'Huawei Technologies Co., Ltd',
  '9C3DCF': 'Samsung Electronics Co., Ltd',
  '9C4178': 'Huawei Technologies Co., Ltd',
  '9C4E20': 'Huawei Technologies Co., Ltd',
  '9C56E6': 'Huawei Technologies Co., Ltd',
  '9C7A03': 'Huawei Technologies Co., Ltd',
  '9CA5C0': 'Huawei Technologies Co., Ltd',
  '9CD35B': 'Samsung Electronics Co., Ltd',
  '9CD48B': 'Huawei Technologies Co., Ltd',
  'A0055C': 'Huawei Technologies Co., Ltd',
  'A015B6': 'Huawei Technologies Co., Ltd',
  'A0369F': 'Intel Corporation',
  'A03B1B': 'Huawei Technologies Co., Ltd',
  'A041A7': 'Huawei Technologies Co., Ltd',
  'A04E01': 'Huawei Technologies Co., Ltd',
  'A058A5': 'Huawei Technologies Co., Ltd',
  'A05DC1': 'Huawei Technologies Co., Ltd',
  'A07771': 'Huawei Technologies Co., Ltd',
  'A0A3F0': 'Huawei Technologies Co., Ltd',
  'A0AFBD': 'Intel Corporation',
  'A0C9A0': 'Huawei Technologies Co., Ltd',
  'A0E25A': 'Huawei Technologies Co., Ltd',
  'A0E5E9': 'Huawei Technologies Co., Ltd',
  'A0EC80': 'Huawei Technologies Co., Ltd',
  'A4A24A': 'Huawei Technologies Co., Ltd',
  'A4B1E9': 'Huawei Technologies Co., Ltd',
  'A4B36A': 'Huawei Technologies Co., Ltd',
  'A4D18C': 'Apple, Inc.',
  'A4D1D2': 'Apple, Inc.',
  'A4D931': 'Huawei Technologies Co., Ltd',
  'A4DCBE': 'Huawei Technologies Co., Ltd',
  'A4E4B8': 'Huawei Technologies Co., Ltd',
  'A4FB8D': 'Huawei Technologies Co., Ltd',
  'A861DF': 'Huawei Technologies Co., Ltd',
  'A865B2': 'Huawei Technologies Co., Ltd',
  'A88CEE': 'Huawei Technologies Co., Ltd',
  'A8A668': 'Apple, Inc.',
  'A8A795': 'Huawei Technologies Co., Ltd',
  'A8B1D4': 'Huawei Technologies Co., Ltd',
  'A8D3F7': 'Huawei Technologies Co., Ltd',
  'A8D828': 'Huawei Technologies Co., Ltd',
  'A8F470': 'Huawei Technologies Co., Ltd',
  'A8FE9E': 'Huawei Technologies Co., Ltd',
  'AC2942': 'Huawei Technologies Co., Ltd',
  'AC3A7A': 'Samsung Electronics Co., Ltd',
  'AC5F3E': 'Huawei Technologies Co., Ltd',
  'AC61EA': 'Apple, Inc.',
  'AC7B61': 'Huawei Technologies Co., Ltd',
  'AC84C6': 'Huawei Technologies Co., Ltd',
  'AC89A4': 'Huawei Technologies Co., Ltd',
  'AC94CC': 'Huawei Technologies Co., Ltd',
  'ACA016': 'Huawei Technologies Co., Ltd',
  'ACB974': 'Huawei Technologies Co., Ltd',
  'ACD1B8': 'Huawei Technologies Co., Ltd',
  'ACD364': 'Huawei Technologies Co., Ltd',
  'ACE215': 'Huawei Technologies Co., Ltd',
  'B019C6': 'Huawei Technologies Co., Ltd',
  'B025AA': 'Huawei Technologies Co., Ltd',
  'B03104': 'Huawei Technologies Co., Ltd',
  'B03956': 'Samsung Electronics Co., Ltd',
  'B03E59': 'Huawei Technologies Co., Ltd',
  'B0525E': 'Huawei Technologies Co., Ltd',
  'B054B9': 'Huawei Technologies Co., Ltd',
  'B065BD': 'Apple, Inc.',
  'B075D5': 'Huawei Technologies Co., Ltd',
  'B0AA77': 'Huawei Technologies Co., Ltd',
  'B0C128': 'Huawei Technologies Co., Ltd',
  'B0C69A': 'Samsung Electronics Co., Ltd',
  'B0D59D': 'Huawei Technologies Co., Ltd',
  'B0DF3A': 'Huawei Technologies Co., Ltd',
  'B0F1EC': 'Huawei Technologies Co., Ltd',
  'B41A1C': 'Huawei Technologies Co., Ltd',
  'B43824': 'Huawei Technologies Co., Ltd',
  'B44506': 'Huawei Technologies Co., Ltd',
  'B44CC2': 'NR Electric Co., Ltd',
  'B451F9': 'Huawei Technologies Co., Ltd',
  'B456E3': 'Huawei Technologies Co., Ltd',
  'B45F22': 'Huawei Technologies Co., Ltd',
  'B462AD': 'Huawei Technologies Co., Ltd',
  'B46D35': 'Huawei Technologies Co., Ltd',
  'B4A5EF': 'Huawei Technologies Co., Ltd',
  'B4A9FC': 'Huawei Technologies Co., Ltd',
  'B4B024': 'Huawei Technologies Co., Ltd',
  'B4EBD5': 'Huawei Technologies Co., Ltd',
  'B4ED19': 'Huawei Technologies Co., Ltd',
  'B4F61C': 'Huawei Technologies Co., Ltd',
  'B808CF': 'Samsung Electronics Co., Ltd',
  'B80B7D': 'Huawei Technologies Co., Ltd',
  'B8186F': 'Huawei Technologies Co., Ltd',
  'B81C85': 'Huawei Technologies Co., Ltd',
  'B83A7B': 'Huawei Technologies Co., Ltd',
  'B84FD5': 'Huawei Technologies Co., Ltd',
  'B85510': 'Huawei Technologies Co., Ltd',
  'B86091': 'Huawei Technologies Co., Ltd',
  'B86CE8': 'Samsung Electronics Co., Ltd',
  'B8782E': 'Huawei Technologies Co., Ltd',
  'B87AC7': 'Huawei Technologies Co., Ltd',
  'B87CF2': 'Apple, Inc.',
  'B8975A': 'Huawei Technologies Co., Ltd',
  'B89AED': 'Huawei Technologies Co., Ltd',
  'B89BC9': 'Huawei Technologies Co., Ltd',
  'B8A3E0': 'Huawei Technologies Co., Ltd',
  'B8B42C': 'Huawei Technologies Co., Ltd',
  'B8BA68': 'Huawei Technologies Co., Ltd',
  'B8BC1B': 'Huawei Technologies Co., Ltd',
  'B8C716': 'Huawei Technologies Co., Ltd',
  'B8D7AF': 'Huawei Technologies Co., Ltd',
  'B8E589': 'Huawei Technologies Co., Ltd',
  'B8F009': 'Huawei Technologies Co., Ltd',
  'B8F6B1': 'Apple, Inc.',
  'B8F828': 'Huawei Technologies Co., Ltd',
  'BC1E85': 'Huawei Technologies Co., Ltd',
  'BC3A2F': 'Huawei Technologies Co., Ltd',
  'BC3BAF': 'Huawei Technologies Co., Ltd',
  'BC4CC4': 'Huawei Technologies Co., Ltd',
  'BC620E': 'Huawei Technologies Co., Ltd',
  'BC6C21': 'Huawei Technologies Co., Ltd',
  'BC7574': 'Huawei Technologies Co., Ltd',
  'BC7670': 'Huawei Technologies Co., Ltd',
  'BC926B': 'Apple, Inc.',
  'BCA8A6': 'Intel Corporation',
  'BCAEC5': 'Huawei Technologies Co., Ltd',
  'BCB181': 'Huawei Technologies Co., Ltd',
  'BCD11F': 'Huawei Technologies Co., Ltd',
  'BCE59F': 'Huawei Technologies Co., Ltd',
  'BCF61C': 'Huawei Technologies Co., Ltd',
  'BCF810': 'Huawei Technologies Co., Ltd',
  'BCFE8C': 'Huawei Technologies Co., Ltd',
  'C019F0': 'Huawei Technologies Co., Ltd',
  'C03170': 'Huawei Technologies Co., Ltd',
  'C049EF': 'Huawei Technologies Co., Ltd',
  'C0766F': 'Huawei Technologies Co., Ltd',
  'C0847A': 'Huawei Technologies Co., Ltd',
  'C08AD0': 'Huawei Technologies Co., Ltd',
  'C09727': 'Huawei Technologies Co., Ltd',
  'C09C04': 'Huawei Technologies Co., Ltd',
  'C0A0C7': 'Huawei Technologies Co., Ltd',
  'C0B4BB': 'Huawei Technologies Co., Ltd',
  'C0B6F9': 'Apple, Inc.',
  'C0BAE6': 'Huawei Technologies Co., Ltd',
  'C0BFD0': 'Huawei Technologies Co., Ltd',
  'C0D044': 'Samsung Electronics Co., Ltd',
  'C0D391': 'Huawei Technologies Co., Ltd',
  'C0E08A': 'Huawei Technologies Co., Ltd',
  'C0EEFB': 'Huawei Technologies Co., Ltd',
  'C0F2FB': 'Apple, Inc.',
  'C4A81D': 'D-Link International',
  'C8D9D2': 'Huawei Technologies Co., Ltd',
  'C8E0EB': 'Apple, Inc.',
  'C8F2BE': 'Huawei Technologies Co., Ltd',
  'C8F68D': 'Huawei Technologies Co., Ltd',
  'C8FE6F': 'Apple, Inc.',
  'CC08FA': 'Huawei Technologies Co., Ltd',
  'CC2D83': 'Huawei Technologies Co., Ltd',
  'CC3AD5': 'Huawei Technologies Co., Ltd',
  'CC4CD4': 'Huawei Technologies Co., Ltd',
  'CC5A53': 'Huawei Technologies Co., Ltd',
  'CC60C8': 'Huawei Technologies Co., Ltd',
  'CC6DA0': 'Huawei Technologies Co., Ltd',
  'CC96A0': 'Huawei Technologies Co., Ltd',
  'CC9F7A': 'Huawei Technologies Co., Ltd',
  'CCA614': 'Huawei Technologies Co., Ltd',
  'CCAF78': 'Huawei Technologies Co., Ltd',
  'CCB11A': 'Huawei Technologies Co., Ltd',
  'CCB255': 'Huawei Technologies Co., Ltd',
  'CCC50A': 'Huawei Technologies Co., Ltd',
  'CCD29B': 'Huawei Technologies Co., Ltd',
  'CCD9A0': 'Huawei Technologies Co., Ltd',
  'CCE2DF': 'Huawei Technologies Co., Ltd',
  'CCEF48': 'Huawei Technologies Co., Ltd',
  'D0176A': 'Huawei Technologies Co., Ltd',
  'D01CBB': 'Huawei Technologies Co., Ltd',
  'D02A4C': 'Huawei Technologies Co., Ltd',
  'D02DB3': 'Huawei Technologies Co., Ltd',
  'D04BFF': 'Huawei Technologies Co., Ltd',
  'D0542D': 'Huawei Technologies Co., Ltd',
  'D058C0': 'Huawei Technologies Co., Ltd',
  'D05A0F': 'Huawei Technologies Co., Ltd',
  'D06F82': 'Huawei Technologies Co., Ltd',
  'D073D5': 'Huawei Technologies Co., Ltd',
  'D07AB3': 'Huawei Technologies Co., Ltd',
  'D07CA8': 'Huawei Technologies Co., Ltd',
  'D0817A': 'Huawei Technologies Co., Ltd',
  'D084F0': 'Huawei Technologies Co., Ltd',
  'D093F8': 'Huawei Technologies Co., Ltd',
  'D09466': 'Huawei Technologies Co., Ltd',
  'D0A637': 'Huawei Technologies Co., Ltd',
  'D0B5C8': 'Huawei Technologies Co., Ltd',
  'D0D0FD': 'Huawei Technologies Co., Ltd',
  'D0D9A3': 'Huawei Technologies Co., Ltd',
  'D0E081': 'Huawei Technologies Co., Ltd',
  'D0EAAB': 'Huawei Technologies Co., Ltd',
  'D0F000': 'Huawei Technologies Co., Ltd',
  'D41AE4': 'Huawei Technologies Co., Ltd',
  'D42C28': 'Huawei Technologies Co., Ltd',
  'D43C88': 'Huawei Technologies Co., Ltd',
  'D449D5': 'Huawei Technologies Co., Ltd',
  'D44B5E': 'Huawei Technologies Co., Ltd',
  'D45C24': 'Huawei Technologies Co., Ltd',
  'D45D42': 'Huawei Technologies Co., Ltd',
  'D461FE': 'Huawei Technologies Co., Ltd',
  'D46706': 'Huawei Technologies Co., Ltd',
  'D46CBF': 'Huawei Technologies Co., Ltd',
  'D47B35': 'Huawei Technologies Co., Ltd',
  'D48B55': 'Huawei Technologies Co., Ltd',
  'D4917C': 'Huawei Technologies Co., Ltd',
  'D494E8': 'Dell Inc.',
  'D4A02A': 'Apple, Inc.',
  'D4A33D': 'Apple, Inc.',
  'D4B43E': 'Huawei Technologies Co., Ltd',
  'D4D748': 'Huawei Technologies Co., Ltd',
  'D4DC23': 'Huawei Technologies Co., Ltd',
  'D4F46F': 'Apple, Inc.',
  'D81C14': 'Huawei Technologies Co., Ltd',
  'D81D72': 'Huawei Technologies Co., Ltd',
  'D82522': 'Huawei Technologies Co., Ltd',
  'D836D7': 'Huawei Technologies Co., Ltd',
  'D83ADD': 'Samsung Electronics Co., Ltd',
  'D841AC': 'Huawei Technologies Co., Ltd',
  'D85C4A': 'Huawei Technologies Co., Ltd',
  'D86162': 'Huawei Technologies Co., Ltd',
  'D86194': 'Huawei Technologies Co., Ltd',
  'D86BF7': 'Huawei Technologies Co., Ltd',
  'D880DC': 'Huawei Technologies Co., Ltd',
  'D88466': 'Huawei Technologies Co., Ltd',
  'D887D5': 'Huawei Technologies Co., Ltd',
  'D88A3B': 'Huawei Technologies Co., Ltd',
  'D8A35D': 'Huawei Technologies Co., Ltd',
  'D8B190': 'Huawei Technologies Co., Ltd',
  'D8C3E8': 'Huawei Technologies Co., Ltd',
  'D8C771': 'Huawei Technologies Co., Ltd',
  'D8D27C': 'Huawei Technologies Co., Ltd',
  'D8D866': 'Huawei Technologies Co., Ltd',
  'D8E0E1': 'Huawei Technologies Co., Ltd',
  'D8EC5E': 'Huawei Technologies Co., Ltd',
  'D8F05A': 'Huawei Technologies Co., Ltd',
  'D8F0F2': 'Huawei Technologies Co., Ltd',
  'D8F3BC': 'Huawei Technologies Co., Ltd',
  'D8FE8F': 'Huawei Technologies Co., Ltd',
  'DC0B1A': 'Huawei Technologies Co., Ltd',
  'DC0D30': 'Huawei Technologies Co., Ltd',
  'DC2B61': 'Apple, Inc.',
  'DC3714': 'Apple, Inc.',
  'DC415F': 'Apple, Inc.',
  'DC4A3E': 'Huawei Technologies Co., Ltd',
  'DC4EDE': 'Huawei Technologies Co., Ltd',
  'DC647C': 'Huawei Technologies Co., Ltd',
  'DC71CE': 'Samsung Electronics Co., Ltd',
  'DC86D8': 'Apple, Inc.',
  'DC9B9C': 'Apple, Inc.',
  'DCA4CA': 'Apple, Inc.',
  'DCA904': 'Huawei Technologies Co., Ltd',
  'DCA989': 'Huawei Technologies Co., Ltd',
  'DCB5B6': 'Huawei Technologies Co., Ltd',
  'DCD321': 'Huawei Technologies Co., Ltd',
  'DCDB70': 'Huawei Technologies Co., Ltd',
  'DCE026': 'Huawei Technologies Co., Ltd',
  'DCEB94': 'Huawei Technologies Co., Ltd',
  'E0286D': 'Huawei Technologies Co., Ltd',
  'E039D7': 'Huawei Technologies Co., Ltd',
  'E05163': 'Huawei Technologies Co., Ltd',
  'E0719E': 'Huawei Technologies Co., Ltd',
  'E079C5': 'Huawei Technologies Co., Ltd',
  'E09DB8': 'Huawei Technologies Co., Ltd',
  'E0A1D7': 'Huawei Technologies Co., Ltd',
  'E0B94D': 'Huawei Technologies Co., Ltd',
  'E0CA94': 'Huawei Technologies Co., Ltd',
  'E0CB1D': 'Apple, Inc.',
  'E0D072': 'Apple, Inc.',
  'E0D0E9': 'Huawei Technologies Co., Ltd',
  'E0D7BA': 'Samsung Electronics Co., Ltd',
  'E0E631': 'Huawei Technologies Co., Ltd',
  'E0ED1A': 'Huawei Technologies Co., Ltd',
  'E0F5CA': 'Huawei Technologies Co., Ltd',
  'E0F847': 'Huawei Technologies Co., Ltd',
  'E414EE': 'Huawei Technologies Co., Ltd',
  'E429F9': 'Huawei Technologies Co., Ltd',
  'E4388C': 'Huawei Technologies Co., Ltd',
  'E43FA2': 'Huawei Technologies Co., Ltd',
  'E446BD': 'Huawei Technologies Co., Ltd',
  'E4496B': 'Huawei Technologies Co., Ltd',
  'E44C6C': 'Huawei Technologies Co., Ltd',
  'E455EA': 'Huawei Technologies Co., Ltd',
  'E45D51': 'Huawei Technologies Co., Ltd',
  'E468A3': 'Huawei Technologies Co., Ltd',
  'E46C21': 'Huawei Technologies Co., Ltd',
  'E48B7F': 'Huawei Technologies Co., Ltd',
  'E4956E': 'Huawei Technologies Co., Ltd',
  'E49EDC': 'Huawei Technologies Co., Ltd',
  'E4A7C3': 'Huawei Technologies Co., Ltd',
  'E4AA5D': 'Huawei Technologies Co., Ltd',
  'E4B2FB': 'Huawei Technologies Co., Ltd',
  'E4B97A': 'Huawei Technologies Co., Ltd',
  'E4CC5B': 'Huawei Technologies Co., Ltd',
  'E4F3E3': 'Huawei Technologies Co., Ltd',
  'E4F89C': 'Huawei Technologies Co., Ltd',
  'E80410': 'Huawei Technologies Co., Ltd',
  'E81249': 'Huawei Technologies Co., Ltd',
  'E81D04': 'Huawei Technologies Co., Ltd',
  'E8447E': 'Huawei Technologies Co., Ltd',
  'E84ECE': 'Huawei Technologies Co., Ltd',
  'E85776': 'Huawei Technologies Co., Ltd',
  'E85AA9': 'Huawei Technologies Co., Ltd',
  'E85D6B': 'Huawei Technologies Co., Ltd',
  'E86A64': 'Huawei Technologies Co., Ltd',
  'E8757F': 'Huawei Technologies Co., Ltd',
  'E8892C': 'Huawei Technologies Co., Ltd',
  'E89796': 'Huawei Technologies Co., Ltd',
  'E89A8F': 'Huawei Technologies Co., Ltd',
  'E89EB4': 'Huawei Technologies Co., Ltd',
  'E8B4AE': 'Huawei Technologies Co., Ltd',
  'E8D85F': 'Huawei Technologies Co., Ltd',
  'E8EB11': 'Huawei Technologies Co., Ltd',
  'E8F1B0': 'Huawei Technologies Co., Ltd',
  'E8F2E2': 'Huawei Technologies Co., Ltd',
  'EC085B': 'Huawei Technologies Co., Ltd',
  'EC0D51': 'Huawei Technologies Co., Ltd',
  'EC1B5F': 'Huawei Technologies Co., Ltd',
  'EC229D': 'Huawei Technologies Co., Ltd',
  'EC24B8': 'Huawei Technologies Co., Ltd',
  'EC2AF0': 'Huawei Technologies Co., Ltd',
  'EC388F': 'Huawei Technologies Co., Ltd',
  'EC3C88': 'Huawei Technologies Co., Ltd',
  'EC3E09': 'Huawei Technologies Co., Ltd',
  'EC438B': 'Huawei Technologies Co., Ltd',
  'EC4D47': 'Huawei Technologies Co., Ltd',
  'EC58EA': 'Huawei Technologies Co., Ltd',
  'EC5C68': 'Huawei Technologies Co., Ltd',
  'EC6E0D': 'Huawei Technologies Co., Ltd',
  'EC86D1': 'Huawei Technologies Co., Ltd',
  'EC89F5': 'Huawei Technologies Co., Ltd',
  'EC8D9C': 'Huawei Technologies Co., Ltd',
  'ECAA25': 'Huawei Technologies Co., Ltd',
  'ECADB8': 'Huawei Technologies Co., Ltd',
  'ECBD09': 'Huawei Technologies Co., Ltd',
  'ECC882': 'Huawei Technologies Co., Ltd',
  'ECE09B': 'Huawei Technologies Co., Ltd',
  'ECE1A9': 'Huawei Technologies Co., Ltd',
  'ECE9F8': 'Huawei Technologies Co., Ltd',
  'ECF4BB': 'Huawei Technologies Co., Ltd',
  'F015A0': 'Huawei Technologies Co., Ltd',
  'F01C13': 'Huawei Technologies Co., Ltd',
  'F0219D': 'Huawei Technologies Co., Ltd',
  'F02408': 'Huawei Technologies Co., Ltd',
  'F0272D': 'Huawei Technologies Co., Ltd',
  'F02F74': 'Apple, Inc.',
  'F033E5': 'Huawei Technologies Co., Ltd',
  'F03E90': 'Huawei Technologies Co., Ltd',
  'F04335': 'Huawei Technologies Co., Ltd',
  'F04B6A': 'Huawei Technologies Co., Ltd',
  'F04BF2': 'Huawei Technologies Co., Ltd',
  'F04DA2': 'Dell Inc.',
  'F0521C': 'Huawei Technologies Co., Ltd',
  'F05C19': 'Huawei Technologies Co., Ltd',
  'F05D89': 'Huawei Technologies Co., Ltd',
  'F077D0': 'Huawei Technologies Co., Ltd',
  'F07D68': 'Huawei Technologies Co., Ltd',
  'F08A28': 'Huawei Technologies Co., Ltd',
  'F0921C': 'Huawei Technologies Co., Ltd',
  'F093C5': 'Huawei Technologies Co., Ltd',
  'F099BF': 'Apple, Inc.',
  'F09CE9': 'Huawei Technologies Co., Ltd',
  'F0A225': 'Huawei Technologies Co., Ltd',
  'F0ACA4': 'Huawei Technologies Co., Ltd',
  'F0B0E7': 'Huawei Technologies Co., Ltd',
  'F0B429': 'Huawei Technologies Co., Ltd',
  'F0C27A': 'Huawei Technologies Co., Ltd',
  'F0C7D7': 'Huawei Technologies Co., Ltd',
  'F0D3E7': 'Huawei Technologies Co., Ltd',
  'F0D7AA': 'Huawei Technologies Co., Ltd',
  'F0DC4A': 'Huawei Technologies Co., Ltd',
  'F0DEF1': 'Huawei Technologies Co., Ltd',
  'F0E6AE': 'Huawei Technologies Co., Ltd',
  'F0ECD2': 'Huawei Technologies Co., Ltd',
  'F0F002': 'Huawei Technologies Co., Ltd',
  'F0F5AE': 'Huawei Technologies Co., Ltd',
  'F0F669': 'Huawei Technologies Co., Ltd',
  'F0F755': 'Huawei Technologies Co., Ltd',
  'F40E11': 'Huawei Technologies Co., Ltd',
  'F41B8C': 'Huawei Technologies Co., Ltd',
  'F41F88': 'Samsung Electronics Co., Ltd',
  'F42771': 'Huawei Technologies Co., Ltd',
  'F42B48': 'Huawei Technologies Co., Ltd',
  'F4323D': 'Huawei Technologies Co., Ltd',
  'F437B7': 'Huawei Technologies Co., Ltd',
  'F43E9D': 'Huawei Technologies Co., Ltd',
  'F44B2A': 'Huawei Technologies Co., Ltd',
  'F44D30': 'Huawei Technologies Co., Ltd',
  'F4559C': 'Huawei Technologies Co., Ltd',
  'F45F69': 'Huawei Technologies Co., Ltd',
  'F46A92': 'Huawei Technologies Co., Ltd',
  'F480C0': 'Huawei Technologies Co., Ltd',
  'F483CD': 'Huawei Technologies Co., Ltd',
  'F4911E': 'Huawei Technologies Co., Ltd',
  'F49F54': 'Huawei Technologies Co., Ltd',
  'F4A52F': 'Huawei Technologies Co., Ltd',
  'F4A80D': 'Huawei Technologies Co., Ltd',
  'F4B301': 'Huawei Technologies Co., Ltd',
  'F4B520': 'Huawei Technologies Co., Ltd',
  'F4B549': 'Huawei Technologies Co., Ltd',
  'F4B7E2': 'Huawei Technologies Co., Ltd',
  'F4BD7C': 'Huawei Technologies Co., Ltd',
  'F4C714': 'Huawei Technologies Co., Ltd',
  'F4D108': 'Huawei Technologies Co., Ltd',
  'F4E3F1': 'Huawei Technologies Co., Ltd',
  'F4E926': 'Huawei Technologies Co., Ltd',
  'F4F26D': 'Huawei Technologies Co., Ltd',
  'F4F5D8': 'Huawei Technologies Co., Ltd',
  'F4FF3F': 'Huawei Technologies Co., Ltd',
  'F80278': 'Huawei Technologies Co., Ltd',
  'F80BCF': 'Huawei Technologies Co., Ltd',
  'F80D43': 'Huawei Technologies Co., Ltd',
  'F80F41': 'Huawei Technologies Co., Ltd',
  'F81409': 'Huawei Technologies Co., Ltd',
  'F81AE5': 'Huawei Technologies Co., Ltd',
  'F81CE5': 'Huawei Technologies Co., Ltd',
  'F82265': 'Huawei Technologies Co., Ltd',
  'F82FA8': 'Huawei Technologies Co., Ltd',
  'F83587': 'Huawei Technologies Co., Ltd',
  'F8436F': 'Huawei Technologies Co., Ltd',
  'F845AD': 'Huawei Technologies Co., Ltd',
  'F84D76': 'Huawei Technologies Co., Ltd',
  'F8516D': 'Huawei Technologies Co., Ltd',
  'F85B9C': 'Huawei Technologies Co., Ltd',
  'F86601': 'Huawei Technologies Co., Ltd',
  'F86A2F': 'Huawei Technologies Co., Ltd',
  'F88E85': 'Huawei Technologies Co., Ltd',
  'F894C2': 'Huawei Technologies Co., Ltd',
  'F895C7': 'Huawei Technologies Co., Ltd',
  'F89E5C': 'Huawei Technologies Co., Ltd',
  'F8A2B4': 'Huawei Technologies Co., Ltd',
  'F8A3AC': 'Huawei Technologies Co., Ltd',
  'F8B156': 'Huawei Technologies Co., Ltd',
  'F8C3CC': 'Huawei Technologies Co., Ltd',
  'F8DB88': 'Huawei Technologies Co., Ltd',
  'F8E4E3': 'Huawei Technologies Co., Ltd',
  'F8F1B3': 'Huawei Technologies Co., Ltd',
  'F8F7D3': 'Huawei Technologies Co., Ltd',
  'F80DAC': 'Huawei Technologies Co., Ltd',
  'F81398': 'Huawei Technologies Co., Ltd',
  'F8B7E2': 'Huawei Technologies Co., Ltd',
  'FCC734': 'Huawei Technologies Co., Ltd',
  'FCE33C': 'Huawei Technologies Co., Ltd',
  'FCE892': 'Huawei Technologies Co., Ltd',
};

// Common vendor shortcuts for well-known OUI prefixes
const wellKnownOuis: Record<string, string> = {
  '00:1B:63': 'Apple Inc.',
  '00:50:F2': 'Microsoft Corporation',
  '00:E0:4C': 'Realtek Semiconductor Corp.',
  '00:08:74': 'Dell Inc.',
  '00:09:5B': 'Netgear Inc.',
  '3C:15:C2': 'Apple, Inc.',
  '40:A6:D9': 'Apple, Inc.',
  '64:B0:A6': 'Apple, Inc.',
  '80:E6:50': 'Apple, Inc.',
  'B0:65:BD': 'Apple, Inc.',
  '00:0C:41': 'Huawei Technologies Co., Ltd',
  '00:0C:76': 'Huawei Technologies Co., Ltd',
  '00:0E:3B': 'Huawei Technologies Co., Ltd',
  '00:1E:64': 'Huawei Technologies Co., Ltd',
  '00:0E:08': 'Dell Inc.',
  '00:14:23': 'Dell Inc.',
  '00:1C:23': 'Dell Inc.',
  '00:0D:A3': 'Dell Inc.',
  '08:00:07': 'Apple Computer, Inc.',
  '00:04:23': 'Intel Corporation',
  '00:07:E9': 'Intel Corporation',
  '00:13:02': 'Intel Corporation',
  '00:15:17': 'Intel Corporation',
  '00:18:DE': 'Intel Corporation',
  '00:1D:E0': 'Intel Corporation',
  '00:1F:3B': 'Intel Corporation',
  '00:24:D7': 'Intel Corporation',
  '00:26:C6': 'Intel Corporation',
  '00:16:CB': 'Apple, Inc.',
  '00:17:F2': 'Apple, Inc.',
  '00:19:CB': 'Apple, Inc.',
  '00:1C:B3': 'Apple, Inc.',
  '00:1F:5B': 'Apple, Inc.',
  '00:21:59': 'Apple, Inc.',
  '00:23:DF': 'Apple, Inc.',
  '00:26:B0': 'Apple, Inc.',
  '00:26:BB': 'Apple, Inc.',
  '00:1B:11': 'D-Link Corporation',
  '00:22:B0': 'D-Link Corporation',
  '00:17:9A': 'D-Link Corporation',
  '08:00:5A': 'IBM Corporation',
  '00:09:6B': 'IBM Corporation',
  '00:01:E6': 'Hewlett Packard',
  '00:10:83': 'Hewlett Packard',
  '08:00:09': 'Hewlett Packard',
  '3C:5A:B4': 'Google, Inc.',
  '4C:0B:BE': 'Xiaomi Communications Co., Ltd',
  '50:A6:7F': 'Xiaomi Inc.',
  '00:13:A9': 'Sony Corporation',
  '00:01:4A': 'Sony Corporation',
  '08:00:3E': 'Motorola',
};

function normalizeMac(mac: string): string {
  // Remove all non-hex characters and convert to uppercase
  const cleaned = mac.replace(/[^0-9A-Fa-f]/g, '').toUpperCase();
  if (cleaned.length !== 12) return '';
  return cleaned.match(/.{2}/g)!.join(':');
}

function extractOui(mac: string): string {
  const cleaned = mac.replace(/[^0-9A-Fa-f]/g, '').toUpperCase();
  if (cleaned.length >= 6) return cleaned.slice(0, 6);
  return cleaned;
}

function lookupVendor(oui: string): string {
  // First check wellKnownOuis by colon format
  const ouiColon = oui.match(/.{2}/g)!.join(':');
  if (wellKnownOuis[ouiColon]) return wellKnownOuis[ouiColon];

  // Check ouiDatabase
  if (ouiDatabase[oui]) return ouiDatabase[oui];

  // Check with first byte masked (for local/private addresses)
  const firstByte = parseInt(oui.slice(0, 2), 16);
  if (firstByte & 0x02) return '本地管理地址 (Locally Administered)';

  return '未在数据库中查找到该厂商信息';
}

function getAddressType(firstByte: number): string {
  if (firstByte & 0x01) return '组播地址 (Multicast)';
  return '单播地址 (Unicast)';
}

function lookup() {
  error.value = '';
  result.value = null;

  const input = macInput.value.trim();
  if (!input) {
    error.value = '请输入 MAC 地址';
    return;
  }

  const normalized = normalizeMac(input);
  if (!normalized) {
    error.value = '无效的 MAC 地址格式：需要 12 个十六进制字符';
    return;
  }

  const ouiRaw = extractOui(input);
  const oui = ouiRaw.match(/.{2}/g)!.join(':');
  const vendor = lookupVendor(ouiRaw);
  const firstByte = parseInt(ouiRaw.slice(0, 2), 16);
  const addressType = getAddressType(firstByte);

  result.value = {
    oui,
    vendor,
    addressType,
    normalized,
  };
}

const formats = computed(() => {
  if (!result.value) return [];
  const mac = result.value.normalized;
  const hex = mac.replace(/:/g, '');
  return [
    { label: '冒号分隔 (xx:xx:xx:xx:xx:xx)', value: hex.match(/.{2}/g)!.join(':').toUpperCase() },
    { label: '短横线分隔 (xx-xx-xx-xx-xx-xx)', value: hex.match(/.{2}/g)!.join('-').toUpperCase() },
    { label: 'Cisco 格式 (xxxx.xxxx.xxxx)', value: hex.match(/.{4}/g)!.join('.').toUpperCase() },
    { label: '无分隔符', value: hex.toUpperCase() },
  ];
});
</script>
